# Use Ubuntu as the base image
FROM ubuntu:latest

# Install dependencies
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:openjdk-r/ppa && \
    apt-get update

# Install Java 8 with IDK 17
RUN apt-get install -y openjdk-8-jdk

# Install Scala 2.11.6
RUN apt-get install wget && \
    wget https://downloads.lightbend.com/scala/2.11.6/scala-2.11.6.tgz && \
    tar -xvzf scala-2.11.6.tgz && \
    mv scala-2.11.6 /usr/lib && \
    ln -s /usr/lib/scala-2.11.6 /usr/lib/scala && \
    rm scala-2.11.6.tgz

# Install Apache Spark 1.3.1
RUN wget https://archive.apache.org/dist/spark/spark-1.3.1/spark-1.3.1-bin-hadoop2.6.tgz && \
    tar -xvzf spark-1.3.1-bin-hadoop2.6.tgz && \
    mv spark-1.3.1-bin-hadoop2.6 /usr/local/spark && \
    rm spark-1.3.1-bin-hadoop2.6.tgz

# Install Python 3.11
RUN apt-get install -y python3.11

# Set environment variables
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV SCALA_HOME /usr/lib/scala
ENV SPARK_HOME /usr/local/spark
ENV PATH $PATH:$JAVA_HOME/bin:$SCALA_HOME/bin:$SPARK_HOME/bin

# Expose Spark UI port
EXPOSE 4040

# Set working directory to Spark home directory
WORKDIR $SPARK_HOME


